# Generated by Django 3.2.7 on 2021-09-12 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_note_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='todo.section'),
        ),
    ]
